<table class="form-list">
	<tr>
		<td class="scope-label">
			<button onclick="setLocation('<?php echo $this->getFlushWsdlCacheUrl()?>')" type="button" class="scalable"><span><span><span><?php echo Mage::helper('adminhtml')->__('Flush WSDL Cache') ?></span></span></span></button>
		</td>
		<td class="scope-label">
			<?php echo Mage::helper('adminhtml')->__('Magento Core API WSDL cache files.')?>
		</td>
	</tr>
</table>